# Generated by Django 4.2.6 on 2023-11-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortlock_app', '0002_alter_usuario_email_alter_usuario_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='senhaMestra',
        ),
    ]
