# Generated by Django 4.2.6 on 2023-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortlock_app', '0003_rename_senha_usuario_senhamestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofre',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
